from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('intermediate/', views.intermediate_view, name='intermediate'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('author_login/', views.author_login, name='author_login'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('author_dashboard/', views.author_dashboard, name='author_dashboard'),
    path('logout/', views.logout_view, name='logout'),
    path('mainuser/', views.mainuser, name='mainuser'),
    path('editor/', views.editor, name='editor'),
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
    path('save_draft/', views.save_draft, name='save_draft'),
    path('add_collaborator/', views.add_collaborator, name='add_collaborator'),
    path('publish/', views.publish_post, name='publish_post'),
    path('blog/<int:post_id>/', views.blog_detail, name='blog_detail'),
    path('notifications/', views.notifications, name='notifications'),
    path('suggestions/', views.suggestions, name='suggestions'),
    path('shop/', views.shop, name='shop'),
    path('about/', views.about, name='about'),
    path('profile/', views.user_profile, name='user_profile'),
    path('author_notifications/', views.author_notifications, name='author_notifications'),
    path('discussions/', views.discussions, name='discussions'),
    path('community/', views.community, name='community'),
    path('community_feed/', views.community_feed, name='community_feed'),
    path('community_discussion/', views.community_discussion, name='community_discussion'),
    path('community_reply/', views.community_reply, name='community_reply'),
    path('community_groups/', views.community_groups, name='community_groups'),
    path('community_join/', views.community_join, name='community_join'),
    path('create_group/', views.create_group, name='create_group'),
    path('settings/', views.settings, name='settings'),
    path('collaboration/', views.collaboration, name='collaboration'),
    path('add_storyboard/', views.add_storyboard, name='add_storyboard'),
    path('edit_storyboard/<int:storyboard_id>/', views.edit_storyboard, name='edit_storyboard'),
    path('view_storyboard/<int:storyboard_id>/', views.view_storyboard, name='view_storyboard'),
    path('add_outline/', views.add_outline, name='add_outline'),
    path('edit_outline/<int:outline_id>/', views.edit_outline, name='edit_outline'),
    path('view_outline/<int:outline_id>/', views.view_outline, name='view_outline'),
    path('upload_asset/', views.upload_asset, name='upload_asset'),
    path('view_asset/<int:asset_id>/', views.view_asset, name='view_asset'),
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post'),
    path('author_profile/', views.author_profile, name='author_profile'),
     path('post/<int:post_id>/', views.post_detail, name='post_detail'),
     path('api/notifications/', views.get_notifications, name='get_notifications'),
     path('api/suggestions/',views.get_suggestions,name='get_suggestions'),
     path('api/author_suggestions/',views.get_suggestions,name='get_suggestions'),
     path('api/submit-author-suggestion/', views.submit_author_suggestion, name='submit_author_suggestion'),
     path('upload_asset/', views.upload_asset, name='upload_asset'),
     path('author/dashboard/', views.author_dashboard, name='author_dashboard'),
     path('author_editor/',views.author_editor,name='author_editor'),
     path('gemini-bot/', views.gemini_bot, name='gemini_bot'),
     path('contact/', views.contact, name='contact'),
     path('discussions/', views.discussions, name='discussions'),

]