# Generated by Django 5.1.6 on 2025-03-30 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='word.post'),
        ),
    ]
