# Generated by Django 5.1.6 on 2025-03-31 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0009_remove_notification_post_alter_notification_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
