# Generated by Django 5.2 on 2025-04-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0014_post_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='plagiarism_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
